# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageSeoInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=255, unique=True, verbose_name='Page URL')),
                ('meta_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta keywords')),
            ],
            options={
                'db_table': 'seo_page_seo_information',
                'ordering': ('-pk',),
                'verbose_name': 'page seo information',
                'verbose_name_plural': 'page seo information',
            },
        ),
    ]
