# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171031_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pk',), 'verbose_name': 'advert', 'verbose_name_plural': 'adverts'},
        ),
    ]
