# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171101_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pk',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
