# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 16:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smmpay.apps.advert.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('advert_type', models.CharField(choices=[('social_account', 'Social account')], default='social_account', max_length=25, verbose_name='type of advert')),
                ('price', models.IntegerField(verbose_name='price')),
                ('views', models.IntegerField(default=0, editable=False, verbose_name='count of views')),
                ('enabled_by_author', models.BooleanField(default=True, verbose_name='enabled by author')),
                ('status', models.CharField(choices=[('published', 'Published'), ('moderation', 'Moderation'), ('violation', 'Violation')], default='moderation', max_length=25, verbose_name='status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name_plural': 'adverts',
                'ordering': ('-pk',),
                'db_table': 'advert_advert',
                'verbose_name': 'advert',
            },
        ),
        migrations.CreateModel(
            name='AdvertSocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=smmpay.apps.advert.helpers.RenameFile('offer/social_accounts/%Y/%m/%d'), verbose_name='logo')),
                ('link', models.URLField(verbose_name='account link')),
                ('subscribers', models.IntegerField(verbose_name='subscribers')),
                ('confirmed', models.BooleanField(default=False, verbose_name='confirmed by author')),
                ('confirmation_code', models.TextField(verbose_name='confirmation code')),
                ('advert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_account', to='advert.Advert', verbose_name='advert')),
            ],
            options={
                'db_table': 'advert_advert_social_account',
            },
        ),
        migrations.CreateModel(
            name='AdvertViewsStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views_statistic', to='advert.Advert')),
            ],
            options={
                'db_table': 'advert_advert_views_statistic',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('title',),
                'db_table': 'advert_category',
                'verbose_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='advert.Advert', verbose_name='advert')),
            ],
            options={
                'verbose_name_plural': 'discussions',
                'ordering': ('pk',),
                'db_table': 'advert_discussion',
                'verbose_name': 'discussion',
            },
        ),
        migrations.CreateModel(
            name='DiscussionMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_messages', to='advert.Discussion', verbose_name='discussion')),
            ],
            options={
                'verbose_name_plural': 'messages',
                'ordering': ('pk',),
                'db_table': 'advert_discussion_message',
                'verbose_name': 'message',
            },
        ),
        migrations.CreateModel(
            name='DiscussionMessageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=True)),
                ('view_date', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='advert.DiscussionMessage')),
            ],
            options={
                'verbose_name_plural': 'views',
                'db_table': 'advert_discussion_message_view',
                'verbose_name': 'view',
            },
        ),
        migrations.CreateModel(
            name='DiscussionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_users', to='advert.Discussion', verbose_name='discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_users', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'discussion users',
                'db_table': 'advert_discussion_user',
                'verbose_name': 'discussion user',
            },
        ),
        migrations.CreateModel(
            name='FavoriteAdvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_adverts', to='advert.Advert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_adverts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'favorite',
                'verbose_name_plural': 'favorites',
                'ordering': ('-pk',),
                'db_table': 'advert_favorite_advert',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('position', models.CharField(choices=[('top_menu', 'Top menu'), ('bottom_menu', 'Bottom menu')], max_length=32, verbose_name='menu position')),
            ],
            options={
                'verbose_name_plural': 'menu',
                'db_table': 'advert_menu',
                'verbose_name': 'menu',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='title')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='advert.Menu', verbose_name='menu')),
            ],
            options={
                'verbose_name_plural': 'menu items',
                'db_table': 'advert_menu_item',
                'verbose_name': 'menu item',
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2, verbose_name='language')),
                ('phrase', models.TextField(verbose_name='phrase')),
            ],
            options={
                'verbose_name_plural': 'phrases',
                'ordering': ('pk',),
                'db_table': 'advert_phrase',
                'verbose_name': 'phrase',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
            ],
            options={
                'verbose_name_plural': 'regions',
                'ordering': ('title',),
                'db_table': 'advert_region',
                'verbose_name': 'region',
            },
        ),
        migrations.CreateModel(
            name='SocialAccountConfirmationQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('success', 'Success'), ('progress', 'In progress'), ('error', 'Error')], default='new', max_length=10, verbose_name='status')),
                ('attempts', models.SmallIntegerField(default=0, verbose_name='attempts count')),
                ('last_start', models.DateTimeField(blank=True, null=True, verbose_name='last start')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.AdvertSocialAccount', verbose_name='social account')),
            ],
            options={
                'db_table': 'advert_advert_social_account_confirmation',
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('code', models.CharField(max_length=25, unique=True, verbose_name='network code')),
                ('urls', models.TextField(verbose_name='URLs')),
                ('order', models.SmallIntegerField(default=0, verbose_name='order')),
            ],
            options={
                'verbose_name_plural': 'social networks',
                'ordering': ('order', 'pk'),
                'db_table': 'advert_social_network',
                'verbose_name': 'social network',
            },
        ),
        migrations.AddField(
            model_name='discussionmessageview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.DiscussionUser'),
        ),
        migrations.AddField(
            model_name='discussionmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.DiscussionUser', verbose_name='message sender'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='users',
            field=models.ManyToManyField(through='advert.DiscussionUser', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.AddField(
            model_name='advertsocialaccount',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_accounts', to='advert.Region', verbose_name='region'),
        ),
        migrations.AddField(
            model_name='advertsocialaccount',
            name='social_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_accounts', to='advert.SocialNetwork', verbose_name='social network'),
        ),
        migrations.AddField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverts', to='advert.Category', verbose_name='category'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteadvert',
            unique_together=set([('advert', 'user')]),
        ),
    ]
