# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-09 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(max_length=80, verbose_name='title'),
        ),
    ]
