# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import smmpay.apps.advert.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.PositiveIntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='count of views'),
        ),
        migrations.AlterField(
            model_name='advertsocialaccount',
            name='logo',
            field=models.ImageField(default='', upload_to=smmpay.apps.advert.helpers.RenameFile('offer/social_accounts/%Y/%m/%d'), verbose_name='logo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertsocialaccount',
            name='subscribers',
            field=models.PositiveIntegerField(verbose_name='subscribers'),
        ),
    ]
