# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_advertviewsstatistic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteadvert',
            options={'ordering': ('-id',), 'verbose_name': 'favorite', 'verbose_name_plural': 'favorites'},
        ),
    ]
