# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_auto_20171120_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
