# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-19 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_auto_20200109_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccountconfirmationqueue',
            name='social_account',
        ),
        migrations.DeleteModel(
            name='SocialAccountConfirmationQueue',
        ),
    ]
