# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_auto_20171123_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('pages', models.TextField(help_text='Url patterns of pages where you would like to see block, each address on new line', verbose_name='pages')),
                ('position', models.CharField(choices=[('sidebar', 'Sidebar'), ('flatpage_sidebar', 'Flatpage sidebar')], help_text='Position on site where block will be rendered', max_length=50, verbose_name='position')),
                ('content', models.TextField(blank=True, default='', verbose_name='block content')),
                ('context_function', models.CharField(blank=True, default='', help_text='Python function that will handle block context before render', max_length=100, verbose_name='context processor')),
                ('template_name', models.CharField(default='', max_length=255, verbose_name='template name')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
            ],
            options={
                'verbose_name_plural': 'content blocks',
                'verbose_name': 'content block',
                'db_table': 'advert_content_block',
            },
        ),
    ]
