# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 12:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smmpay.apps.advert.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_auto_20171030_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='advert_type',
            field=models.CharField(choices=[('social_account', 'Social account')], default='social_account', max_length=25, verbose_name='type of advert'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverts', to='advert.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='enabled_by_admin',
            field=models.BooleanField(default=False, verbose_name='enabled by admin'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='enabled_by_author',
            field=models.BooleanField(default=True, verbose_name='enabled by author'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.IntegerField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='views',
            field=models.IntegerField(default=0, editable=False, verbose_name='count of views'),
        ),
        migrations.AlterField(
            model_name='advertsocialaccount',
            name='advert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_account', to='advert.Advert', verbose_name='advert'),
        ),
        migrations.AlterField(
            model_name='advertsocialaccount',
            name='confirmation_code',
            field=models.TextField(verbose_name='confirmation code'),
        ),
        migrations.AlterField(
            model_name='advertsocialaccount',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='confirmed by author'),
        ),
        migrations.AlterField(
            model_name='advertsocialaccount',
            name='link',
            field=models.URLField(verbose_name='account link'),
        ),
        migrations.AlterField(
            model_name='advertsocialaccount',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=smmpay.apps.advert.helpers.RenameFile('offer/social_accounts/%Y/%m/%d'), verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='advertsocialaccount',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_accounts', to='advert.Region', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='advertsocialaccount',
            name='social_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_accounts', to='advert.SocialNetwork', verbose_name='social network'),
        ),
        migrations.AlterField(
            model_name='advertsocialaccount',
            name='subscribers',
            field=models.IntegerField(verbose_name='subscribers'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='advert.Advert', verbose_name='advert'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='users',
            field=models.ManyToManyField(through='advert.DiscussionUser', to=settings.AUTH_USER_MODEL, verbose_name='users'),
        ),
        migrations.AlterField(
            model_name='discussionmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='discussionmessage',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_messages', to='advert.Discussion', verbose_name='discussion'),
        ),
        migrations.AlterField(
            model_name='discussionmessage',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='discussionmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.DiscussionUser', verbose_name='message sender'),
        ),
        migrations.AlterField(
            model_name='discussionuser',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_users', to='advert.Discussion', verbose_name='discussion'),
        ),
        migrations.AlterField(
            model_name='discussionuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_users', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='position',
            field=models.CharField(choices=[('top_menu', 'Top menu'), ('bottom_menu', 'Bottom menu')], max_length=32, verbose_name='menu position'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=64, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='advert.Menu', verbose_name='menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=64, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='language',
            field=models.CharField(max_length=2, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='phrase',
            field=models.TextField(verbose_name='phrase'),
        ),
        migrations.AlterField(
            model_name='region',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='socialaccountconfirmationqueue',
            name='attempts',
            field=models.SmallIntegerField(default=0, verbose_name='attempts count'),
        ),
        migrations.AlterField(
            model_name='socialaccountconfirmationqueue',
            name='last_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last start'),
        ),
        migrations.AlterField(
            model_name='socialaccountconfirmationqueue',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.AdvertSocialAccount', verbose_name='social account'),
        ),
        migrations.AlterField(
            model_name='socialaccountconfirmationqueue',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('success', 'Success'), ('progress', 'In progress'), ('error', 'Error')], default='new', max_length=10, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='code',
            field=models.CharField(max_length=25, unique=True, verbose_name='network code'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='urls',
            field=models.TextField(verbose_name='URLs'),
        ),
    ]
