# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_contentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='patterns',
            field=models.TextField(default='', help_text='Python regexp patterns for validation, one per line. Format ^...$', verbose_name='URL patterns'),
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='valid_pattern',
            field=models.CharField(default='', help_text='Valid url pattern of social network, uses in validation errors', max_length=255, verbose_name='Valid url pattern'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='context_function',
            field=models.CharField(blank=True, default='', help_text='Python function that will handle block context before render', max_length=100, verbose_name='context function'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='position',
            field=models.CharField(choices=[('sidebar', 'Sidebar'), ('header_menu', 'Header menu'), ('footer_menu', 'Footer menu')], help_text='Position on site where block will be rendered', max_length=50, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='template_name',
            field=models.CharField(blank=True, default='', help_text='In case field empty, default template advert/tags/content_block/`position`_default.html will be used', max_length=255, verbose_name='template name'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='urls',
            field=models.TextField(help_text='Valid social network hosts, one host per line', verbose_name='URLs'),
        ),
    ]
