# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-01 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_advert_for_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='max_price',
        ),
    ]
