# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import smmpay.apps.advert.models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0005_auto_20171201_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertsocialaccount',
            name='link',
            field=models.URLField(validators=[smmpay.apps.advert.models.validate_social_network_link], verbose_name='account link'),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='code',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
