# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-01 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0005_remove_advert_max_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='min_price',
            new_name='price',
        ),
    ]
