# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-01 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0006_auto_20200601_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='price',
            field=models.PositiveIntegerField(verbose_name='price'),
        ),
    ]
