# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0006_auto_20171212_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopAdvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField()),
                ('advert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='top_advert', to='advert.Advert')),
            ],
            options={
                'db_table': 'advert_top_advert',
                'ordering': ('-advert',),
            },
        ),
        migrations.CreateModel(
            name='VipAdvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField()),
                ('advert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip_advert', to='advert.Advert')),
            ],
            options={
                'db_table': 'advert_vip_advert',
                'ordering': ('-advert',),
            },
        ),
    ]
