# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0006_auto_20171101_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='enabled_by_admin',
        ),
        migrations.AddField(
            model_name='advert',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('moderation', 'Moderation'), ('violation', 'Violation')], default='moderation', max_length=25, verbose_name='status'),
        ),
    ]
