# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0007_topadvert_vipadvert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertsocialaccount',
            options={'verbose_name': 'advert social account', 'verbose_name_plural': 'advert social accounts'},
        ),
        migrations.AlterModelOptions(
            name='topadvert',
            options={'ordering': ('-advert_id',), 'verbose_name': 'top advert', 'verbose_name_plural': 'top adverts'},
        ),
        migrations.AlterModelOptions(
            name='vipadvert',
            options={'ordering': ('-advert_id',), 'verbose_name': 'vip advert', 'verbose_name_plural': 'vip adverts'},
        ),
        migrations.AlterField(
            model_name='favoriteadvert',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_adverts', to='advert.Advert', verbose_name='advert'),
        ),
        migrations.AlterField(
            model_name='favoriteadvert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_adverts', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='socialaccountconfirmationqueue',
            name='social_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='advert.AdvertSocialAccount', verbose_name='social account'),
        ),
        migrations.AlterField(
            model_name='topadvert',
            name='advert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='top_advert', to='advert.Advert', verbose_name='advert'),
        ),
        migrations.AlterField(
            model_name='topadvert',
            name='date_end',
            field=models.DateTimeField(verbose_name='date end'),
        ),
        migrations.AlterField(
            model_name='topadvert',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date start'),
        ),
        migrations.AlterField(
            model_name='vipadvert',
            name='advert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vip_advert', to='advert.Advert', verbose_name='advert'),
        ),
        migrations.AlterField(
            model_name='vipadvert',
            name='date_end',
            field=models.DateTimeField(verbose_name='date end'),
        ),
        migrations.AlterField(
            model_name='vipadvert',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date start'),
        ),
    ]
